# Generated by Django 5.2.6 on 2025-10-27 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del personaje.', max_length=100)),
                ('role', models.CharField(help_text='Rol o descripción del personaje.', max_length=100)),
                ('biography', models.TextField(help_text='Trasfondo corto, personalidad general.')),
                ('key_traits', models.JSONField(blank=True, default=list, help_text="Lista de rasgos clave (ej. ['Lógico', 'Sarcástico', 'Obsesivo'])")),
                ('speech_tics', models.JSONField(blank=True, default=list, help_text="Muletillas o frases comunes (ej. ['Bazinga!', 'Interesante.', 'Eso es mi sitio.'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='app.character'),
        ),
    ]
