# Generated by Django 5.2.6 on 2025-11-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_character_conversation_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-created_at'], 'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.character'),
        ),
    ]
