# Generated by Django 5.2.6 on 2025-11-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_character_options_alter_conversation_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vector_db_name',
            field=models.CharField(blank=True, help_text='Nombre de la base de datos vectorial para RAG', max_length=150),
        ),
    ]
